# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'dono' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for dono
  
  # Piwik
  pod 'PiwikTracker'
  pod 'PiwikTracker/AFNetworking2'
  
  # Facebook
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  

  target 'donoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'donoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
